max_action_dim: 24
max_state_dim: 24
max_views: 3
data_groups:
  franka_joint_angle:
    close_box_120:
      path: /home/dell/code/znb/Evo_depth/datasets/
      view_map:
        image_1: observation.images.image_1
        image_2: observation.images.image_4
        image_3: observation.images.image_5
