max_action_dim: 24
max_state_dim: 24
max_views: 3
data_groups:
  libero_robot:
  
    libero_spatial_no_noops_1.0.0_lerobot:
      path: /home/bozhao/code/ljt/Evo_da3_film_true_else/datasets
      view_map:
        image_1: observation.images.image
        image_2: observation.images.wrist_image

    # libero_object_no_noops_1.0.0_lerobot:
    #   path: /share/jitingliu/Projects/Datasets/libero/libero_object_no_noops_1.0.0_lerobot
    #   view_map:
    #     image_1: observation.images.image
    #     image_2: observation.images.wrist_image

    # libero_goal_no_noops_1.0.0_lerobot:
    #   path: /share/jitingliu/Projects/Datasets/libero/libero_goal_no_noops_1.0.0_lerobot
    #   view_map:
    #     image_1: observation.images.image
    #     image_2: observation.images.wrist_image
      
    # libero_10_no_noops_1.0.0_lerobot:
    #   path: /share/jitingliu/Projects/Datasets/libero/libero_10_no_noops_1.0.0_lerobot
    #   view_map:
    #     image_1: observation.images.image
    #     image_2: observation.images.wrist_image